import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next JS Blog Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${heebo.className} bg-lightbackground text-lightforeground dark:bg-darkbackground dark:text-darkforeground`}
      >
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
