import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const heebo = Heebo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next JS Blog Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
